---
swagger: "2.0"
info:
  version: 1.0-SNAPSHOT
  title: “lesson 2”
basePath: /v1
paths:
  /accounts/{id}:
    get:
      description: Simple get balance functionality.
      operationId: getBalance
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200:
          description: empty response
  /accounts:
    post:
      description: Create Account
      operationId: accounts/createAccount
      parameters:
      - in: query
        name: customerId
        type: integer
        description: Customer Id
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200:
          description: empty response
    get:
      description: Querys accounts
      operationId: accounts/queryAccount
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: customerId
        type: integer
        description: Customer Id
      responses:
        200:
          description: This field was not specified
